### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by ifjera** [TheCherno/Walnut#3]
Hi, it compiles and works with windows 10, but not when compiling with vs 2022 and windows 11, as it complains that imguid.lib functions are already in ImGui.lib.

**Comment by bolshoytoster** [comment]
@ifjera could you paste the (full) error here please.

**Comment by ifjera** [comment]
@bolshoytoster 

It builds just fine if I remove the dependency and link directly to the .lib  
![image](https://user-images.githubusercontent.com/54514959/163765851-d887f77a-7b17-4f9e-8be5-bdada25d5f4d.png)

**Comment by bolshoytoster** [comment]
@ifjera I think you should open an issue in [imgui's repo](https://github.com/ocornut/imgui).

**Comment by BrennenSprimont** [comment]
I was able to build on windows 11 with vs 2022 build tools without fiddling with any dependencies.

If this issue pops up again for you or anyone else.

When you build, there should be a log somewhere stating the exact call to link.exe (below is what msbuild outputs). If you see imgui in here twice, then you have something funky going on in your project. You may have to fiddle with visual studio's settings to turn on these log levels though (https://stackoverflow.com/questions/19822603/is-there-a-way-to-get-the-build-command-line-used-by-visual-studio). Or just call msbuild directly (no arguments are needed, just navigate to the folder the *.sln file is in and run "msbuild").
```
...
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE 
  /OUT:"..\bin\Debug-windows-x86_64\WalnutApp\WalnutApp.exe" /INCREMENTAL /ILK:"..\bin-int\Debug-windows-x86_64\WalnutApp\WalnutApp.ilk 
  " /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32 
  .lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"..\bin\Debug-windows-x86_6 
  4\WalnutApp\WalnutApp.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"..\bin\Debug-windows-x86_64\WalnutApp\WalnutAp 
  p.lib" /MACHINE:X64 "..\bin-int\Debug-windows-x86_64\WalnutApp\WalnutApp.obj"
  "C:\repos\Walnut\vendor\imgui\bin\Debug-windows-x86_64\ImGui\ImGui.lib"
  "C:\repos\Walnut\vendor\glfw\bin\Debug-windows-x86_64\GLFW\GLFW.lib"
  "C:\repos\Walnut\Walnut\bin\Debug-windows-x86_64\Walnut\Walnut.lib"
  WalnutApp.vcxproj -> C:\repos\Walnut\bin\Debug-windows-x86_64\WalnutApp\WalnutApp.exe
...
```

**Comment by ifjera** [comment]
@BrennenSprimont Thank You for the tips: 
My link was   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"..\bin\Deb
  ug-windows-x86_64\WalnutApp\WalnutApp.exe" /INCREMENTAL /ILK:"..\bin-int\Debug-windows-x86_64\WalnutApp\WalnutApp.ilk" /NOLOGO /LIBPATH:"D:\src
  \vcpkg\installed\x64-windows\debug\lib" /LIBPATH:"D:\src\vcpkg\installed\x64-windows\debug\lib\manual-link" kernel32.lib user32.lib gdi32.lib w
  inspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "D:\src\vcpkg\installed\x64-windows\d
  ebug\lib\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"..\bin\Debug-windows-x86_64\WalnutApp\
  WalnutApp.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"..\bin\Debug-windows-x86_64\WalnutApp\WalnutApp.lib" /MACHINE:X64 ".
  .\bin-int\Debug-windows-x86_64\WalnutApp\WalnutApp.obj"
  "D:\code\github\theCherno\WalnutErr\vendor\imgui\bin\Debug-windows-x86_64\ImGui\ImGui.lib"
  "D:\code\github\theCherno\WalnutErr\vendor\glfw\bin\Debug-windows-x86_64\GLFW\GLFW.lib"
  "D:\code\github\theCherno\WalnutErr\Walnut\bin\Debug-windows-x86_64\Walnut\Walnut.lib"
Then I realized the issue was that it looked in vcpkg first, I deleted that imguid.lib there and it worked!! I am closing this issue
