### ISSUE TITLE
Cloning Problem

### ISSUE THREAD

**Issue by MiyazakiMehmet** [TheCherno/Walnut#39]
I'm having an issue with cloning walnut.
When i type `git clone --recursive https://github.com/TheCherno/Walnut`

I'm getting this message:
`Cloning into 'Walnut'...
fatal: unable to access 'https://github.com/TheCherno/Walnut/': Failed to connect to 127.0.0.1 port 1080 after 2057 ms: Connection refused`

I'm kinda new about these topics so I tried to solve this problem but i could not find any solution can someone help me with that?

Also I tried to clone it with SSH key but I also get the same message while it is downloading the submodules.

**Comment by VagueLobster** [comment]
That's because you're trying to clone a "directory", which is not valid.... what you want is this:
git clone --recursive https://github.com/TheCherno/Walnut.git
The line above should do the work to get you going 😉

**Comment by MiyazakiMehmet** [comment]
Unfortunately, it did not work for me I am still having the same issue. :(

**Comment by VagueLobster** [comment]
that sounds very weird 🤔 it should work...
Are you sure you wrote this line in command prompt:
`git clone --recursive https://github.com/TheCherno/Walnut.git`
?

**Comment by MiyazakiMehmet** [comment]
Yes, I wrote the same command.

**Comment by VagueLobster** [comment]
that makes no sense that it won't work... then i'm at a loss 🤷

**Comment by jcs090218** [comment]
Nothing wrong with the command, maybe the proxy issue? See https://stackoverflow.com/questions/24543372/unable-to-connect-to-git-remote-repository.

**Comment by MiyazakiMehmet** [comment]
> Nothing wrong with the command, maybe the proxy issue? See https://stackoverflow.com/questions/24543372/unable-to-connect-to-git-remote-repository.

Yes, as you said the problem was the proxy issue. But the solutions was not fixing my problem like:

```
git config --global --unset http.proxy

git config --global --unset https.proxy
```

So instead, I fixed the problem like this: (Since these do not reset the proxy for certain domain like github.com)

`git config --global --unset http.https://github.com.proxy`

I hope this helps who cannot fix the problem yet.
