### ISSUE TITLE
[vulkan] Error: VkResult = -6

### ISSUE THREAD

**Issue by min-graphics** [TheCherno/Walnut#46]
Dear Cherno
How are you, Cherno.

I am learning your course which teaches us building a ray tracer used Walnut as ui module.
But when i run walnut,there are some trouble that I cant solve.
when i push F5, it occurs that image
![image](https://user-images.githubusercontent.com/94882240/230779593-6951b63c-e86c-4204-af2b-d1f6da6e0f73.png)
and the cmd shows “[vulkan] Error: VkResult = -6”，as we can see from the below image
![image](https://user-images.githubusercontent.com/94882240/230779659-d5d3b149-0a72-4e21-8677-70804e7de011.png)

My English is poor,I'm sorry it may confused you.And i am looking forward to your help. I would also appriacite it if anyone else who will do me a favour.
Yours，
Armin

**Comment by VagueLobster** [comment]
I could find this by searching on google: [https://community.khronos.org/t/vk-error-layer-not-present-error/108749](https://community.khronos.org/t/vk-error-layer-not-present-error/108749)

Sascha Willems is saying this:
> The code above only enables the validation layers, and if that fails it’s probably because you haven’t installed the validation layers e.g. by installing LunarG’s Vulkan SDK.

I don't know if this is your exact problem, but maybe try and look into it?!

**Comment by min-graphics** [comment]
> I could find this by searching on google: https://community.khronos.org/t/vk-error-layer-not-present-error/108749
> 
> Sascha Willems is saying this:
> 
> > The code above only enables the validation layers, and if that fails it’s probably because you haven’t installed the validation layers e.g. by installing LunarG’s Vulkan SDK.
> 
> I don't know if this is your exact problem, but maybe try and look into it?!

Dear VagueLobster:

Thanks for your kindness and warm-heart.

long time ago(about 1 year) , I had installed vulkan SDK. After a system crush,I rebuild my windows system,So I think maybe at that time, the environment of Vulkan has been lost.
Anyway ,I take your advice and reinstall vulkan the later version ,And it work.

I am very very gratitude to you for helping me. It means a lot for me a vulkan rookie who is in some trouble.Hope you have a nice day .

Yours sincerely,
Armin

**Comment by VagueLobster** [comment]
No problem 👍 The important thing is that it works now 😄
