### ISSUE TITLE
LNK1104 cannot open file \Walnut\vendor\imgui\bin\Debug-windows-x86_64\ImGui\ImGui.lib

### ISSUE THREAD

**Issue by CreativelyBad** [TheCherno/Walnut#48]
Is anyone able to tell me if this is a mistake I'm making? I'm pretty new to C++ so maybe this is a really easy fix.

**Comment by VagueLobster** [comment]
it sounds like you forgot to clone the Walnut repository with --recursive

**Comment by CreativelyBad** [comment]
> it sounds like you forgot to clone the Walnut repository with --recursive

Yup that solved it. Thanks for the help!
