### ISSUE TITLE
Cannot find WalnutApp.exe on build

### ISSUE THREAD

**Issue by CyberDudeJ** [TheCherno/Walnut#57]
![image](https://github.com/StudioCherno/Walnut/assets/65360930/3bd3914d-1f03-4ae9-ab4f-e65f4f48bde6)
Oh and, vulkan/vulkan.h cannot be found during build

![image](https://github.com/StudioCherno/Walnut/assets/65360930/f8d04a18-5ba0-42d7-93cc-366443e54bb1)

**Comment by CyberDudeJ** [comment]
Honestly, I'm probably super blind and forgotten to do something.

**Comment by Acromatic** [comment]
vulkan is provided by openGL... go download it, install it somewhere and add the "include" and lib name in VCS... it's not precompiled into walnut. I wouldn't use vcpkg for this one either, just do the manual install of vulkan SDK yourself from the website and ask google how to link it.

**Comment by CyberDudeJ** [comment]
👍 Thanks - I knew I missed something.

> this is not a bug, it's a feature... actually it's a missing dependancy
> 
> vulkan is provided by openGL... go download it, install it somewhere and add the "include" and lib name in VCS... it's not precompiled into walnut. I wouldn't use vcpkg for this one either, just do the manual install of vulkan SDK yourself from the website and ask google how to link it.
> 
> [Moderator] you should respond and lock it.

**Comment by VagueLobster** [comment]
> vulkan is provided by openGL...

This couldn't be more wrong 😆 Vulkan is provided by Khronos, which is also the company that made OpenGL 😉
