### ISSUE TITLE
Does the CPU/GPU need to support Vulkan to be able to run Walnut Applications?

### ISSUE THREAD

**Issue by nyaruku** [TheCherno/Walnut#59]
Question

**Comment by Acromatic** [comment]
walnut is coded for vulkan, but you could recode it for any GFX driver I imagine, however I suspect it's so intertwined that wouldn't be worth it for most people. In reality if you were to do that it'd only serve as a confusing encoded design concept, walnut is basically just a 2d gfx engine without any game elements.. it's a software design suite for vulkan.. it won't serve you well to use other GFX engines but it technically could be changed to do so.

**Comment by nyaruku** [comment]
as my Laptop doesn't support Vulkan, and i would really like to make Desktop Applications with that

**Comment by Acromatic** [comment]
> as my Laptop doesn't support Vulkan, and i would really like to make Desktop Applications with that

that is unfortunate but enlightening, I didn't make walnut but I was attempting to make a plugin framework, which is notoriously difficult with c++, I failed at that but as I was reading the source I noticed it derives from the imgui examples, as most libraries do, in there you will find a direct X example, and if your laptop doesn't support that then it doesn't support hardware accelerated gfx, which is what this does, it's essentially it's own image framework engine, normally you would use windows to do this, or some software graphics driver. more than likely in your case that is so outdated of a concept that it wouldn't even do you any good, as even with the SDL example "simple dynamic layer" microsoft software driver, it'll be replaced probably even before your laptop stops working.
