### ISSUE TITLE
Sample Source for Forest Launcher 

### ISSUE THREAD

**Issue by michalss** [TheCherno/Walnut#64]
Hello,

Can we get sample Forest Launcher source please ? Im after the design, since its not using docking...

Thank you

**Comment by michalss** [comment]
I'm not sure if I explained myself correctly. There are some applications where you don't need docking, while others require docking. I like the design and the Walnut idea, but I've tried to remove docking or, to put it simply, create only one single static dock where you cannot move it or perform any transformations on it. My goal is to create a single MainForm application, similar to what Cherno has in this screenshot. That's all. Even the ImGui GitHub is flooded with these questions, so it doesn't seem to be something easy, I guess. I'm pretty new to C++, so if my question isn't clear, I'm very sorry. I'm doing my best to explain my needs. Also, I'm not a native English speaker.

**Comment by michalss** [comment]
![image](https://github.com/StudioCherno/Walnut/assets/1000729/596693fe-5d54-4c75-a5e6-bed6500e552f)

I meant something like this. I don't specifically need the source code, just guidance on how to do it. Some sample code would be nice ;)

**Comment by Acromatic** [comment]
"Some sample code would be nice" XD... that's what Walnut is... and yes it's EXTREMELY difficult and I've been a student of C++ for 15 years... even I'm struggling to get that far and I did it with irrlicht 15 years ago.... like I said in the duplicate post, this is something we can throw to the check board but it's not likely they will add this quickly, as it's not a quick thing to post, and who knows if "the forest" launcher even still exists. It seems to me in the ImGui Demo there is a switch to disable docking... look into it.

**Comment by Acromatic** [comment]
imguiWindow->disableMove
imguiWindow->disableResize
imguiWindow->disableMinMax

Some psuedo code to consider.

**Comment by michalss** [comment]
Well you can say that i'm not good enough, it could be but i can write in 6 languages and im picking things pretty fast. Anyway sorted.. Thx

**Comment by Acromatic** [comment]
> Well you can say that i'm not good enough, it could be but i can write in 6 languages and im picking things pretty fast. Anyway sorted.. Thx

If that is all anyone can take of the hours I put in trying to help them... then no, thank you, because I will never again in my life waste my time on someone like you again.

**Comment by michalss** [comment]
You are so aggressive person, not sure what is your problem. I did ask nicely for help, Your answer where more than horrible and not polite at all. Read your prev. messages  again ull see how much aggressive person you are. And it is not only in this Issue.. why did you reply to my issue on the first place then. Your 15 years of experience , even with 50 years of experience not giving you right to act like this. So yes it is sorted but not with your help. So If you spend an hour on my question with 15years of experience, you probably doing something wrong there. That's it and to be honest this is my first so negative experience on github , i did not know that is even possible.... :( so sad All of that was so unnecessary...

**Comment by Acromatic** [comment]
> You are so aggressive person, 

I have every right to be as aggressive as I like... that's a subjective personal opinion anyway. If you want to know why it's because you need to go learn C++ first, and stop using this like a forum.. it's not for messages like this. Ok I'm aggressive sure, but you're naive and a complete pain in the ass, you're lucky the internet is now controlled by wimps like you or you'd find out just how aggressive I can really get.
