### ISSUE TITLE
Walnut::Image::SetData() seems to leak memory

### ISSUE THREAD

**Issue by Mikewando** [TheCherno/Walnut#7]
Peremptory thanks, for putting this together. My experience so far has been vastly more enjoyable than previous forays into complex GUI apps.

The only snag I've hit so far is that using the `Walnut::Image` class for dynamically generated image data by calling `SetData()` (e.g. in `OnUIRender()`) seems to leak memory and eventually the app crashes. This can be observed even while passing data that does not actually change (i.e. using the same pointer for every `SetData()` call).

I looked at the code, but I have no Vulkan experience and only pretty rusty C++ experience so nothing stood out to me.

**Comment by Mikewando** [comment]
So actually a little more guessing and checking it seems like the leak stems from the `VkCommandBuffer` which never gets freed. `Application::GetCommandBuffer()` calls `vkAllocateCommandBuffer()` but there is never a corresponding `vkFreeCommandBuffers()` called. I assume this should be done in `Application::FlushCommandBuffer()` or with a new explicit method (e.g. `Application::FreeCommandBuffer()`.

One potentially complicating thing is that the `vkFreeCommandBuffers()` method requires that you provide the same `VkCommandPool` that was used to allocate the buffer. Right now that pool isn't explicitly returned or stored by `Application::GetCommandBuffer()`. I just used the same `wd->Frames[wd->FrameIndex].CommandPool` in `FlushCommandBuffer` as was used in `GetCommandBuffer` and my app hasn't crashed yet, but I don't really know what ImGui is doing or what guarantees are made around when that would change.

**Comment by mwindowshz** [comment]
> So actually a little more guessing and checking it seems like the leak stems from the `VkCommandBuffer` which never gets freed. `Application::GetCommandBuffer()` calls `vkAllocateCommandBuffer()` but there is never a corresponding `vkFreeCommandBuffers()` called. I assume this should be done in `Application::FlushCommandBuffer()` or with a new explicit method (e.g. `Application::FreeCommandBuffer()`).
> 
> One potentially complicating thing is that the `vkFreeCommandBuffers()` method requires that you provide the same `VkCommandPool` that was used to allocate the buffer. Right now that pool isn't explicitly returned or stored by `Application::GetCommandBuffer()`. I just used the same `wd->Frames[wd->FrameIndex].CommandPool` in `FlushCommandBuffer` as was used in `GetCommandBuffer` and my app hasn't crashed yet, but I don't really know what ImGui is doing or what guarantees are made around when that would change.

Can you post the code you fixed?
Also having the memoty leak.

Another issue I want to render live video. so need to call SetData() each time, to update the frame.
Is there a way to avoid this allocation and uploading to gpu, by sending some "pointer" to the image and the Walnut::Image will draw the updated image, without the call of SetData() and its realloction, I find significant CPU usage with my app. that was not there before.

**Comment by Mikewando** [comment]
@mwindowshz
```diff
--- a/Walnut/src/Walnut/Application.cpp
+++ b/Walnut/src/Walnut/Application.cpp
@@ -691,6 +696,9 @@ namespace Walnut {
                check_vk_result(err);

                vkDestroyFence(g_Device, fence, nullptr);
+               ImGui_ImplVulkanH_Window* wd = &g_MainWindowData;
+               VkCommandPool command_pool = wd->Frames[wd->FrameIndex].CommandPool;
+               vkFreeCommandBuffers(g_Device, command_pool, 1, &commandBuffer);
        }
```

**Comment by TheCherno** [comment]
Fixed in https://github.com/TheCherno/Walnut/commit/1f18ebbd073b9ddf3246c5c120d8dd5ef0b53ec1

**Comment by TheCherno** [comment]
@mwindowshz please open another issue for your live video rendering request
