### ISSUE TITLE
Crash when updating image data 

### ISSUE THREAD

**Issue by mwindowshz** [TheCherno/Walnut#9]
I am trying to render video. 
I create one Image and call setData to update image data.

When I change screen size there is a crash. 
the crash is related to this [1f18ebb]( https://github.com/TheCherno/Walnut/commit/1f18ebbd073b9ddf3246c5c120d8dd5ef0b53ec1) 

the code adds freeing of command buffer
```
// Free command buffers allocated by Application::GetCommandBuffer
auto& allocatedCommandBuffers = s_AllocatedCommandBuffers[wd->FrameIndex];
if (allocatedCommandBuffers.size() > 0)
{
	vkFreeCommandBuffers(g_Device, fd->CommandPool, (uint32_t)allocatedCommandBuffers.size(), allocatedCommandBuffers.data());
	allocatedCommandBuffers.clear();
}
```
This works. However When changing the main glfw window size with mouse, there is a crash at vulkan, In these lines
this happend if I change the image using SetData() in the Layers OnUIRender()

> [vulkan] Debug report from ObjectType: 6
> Message: Validation Error: [ VUID-vkFreeCommandBuffers-pCommandBuffers-00048 ] Object 0: handle = 0x18ef04b5820, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x1eb50db9 | Invalid VkCommandBuffer 0x18ef04b5820[]. The Vulkan spec states: pCommandBuffers must be a valid pointer to an array of commandBufferCount VkCommandBuffer handles, each element of which must either be a valid handle or NULL (https://vulkan.lunarg.com/doc/view/1.2.154.1/windows/1.2-extensions/vkspec.html#VUID-vkFreeCommandBuffers-pCommandBuffers-00048)
> 
> [vulkan] Debug report from ObjectType: 6
> Message: Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x18ef04b5820, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x5d6b67e2 | Couldn't find VkCommandBuffer Object 0x18ef04b5820. This should not happen and may indicate a bug in the application.
> 
> [vulkan] Debug report from ObjectType: 6
> Message: Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x18ef04b5820, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x5d6b67e2 | Couldn't find VkCommandBuffer Object 0x18ef04b5820. This should not happen and may indicate a bug in the application.

I am not an expert with vulkan, but if I understand each time we setData() to the image, askes for the CommandBuffer and directions are written to copy the data.

What I don't understand is since everything is executed line after line in Run()  loop , so we first run over layers and call 
```
for (auto& layer : m_LayerStack)
	layer->OnUIRender();
```
and then there is a call to
` FrameRender(wd, main_draw_data);`
which renders and access command buffer and clears it. (by the code above) but it crashes here.

so there is some event on window change, that happens concurrently 

this code reproduces the problem

```
#include "..\..\vendor\stb_image\stb_image.h"
class ExampleLayer : public Walnut::Layer
{
public:
	std::string m_file_name = "C:\\Users\\meir\\Pictures\\vlcsnap-2022-03-16-10h43m50s464.png";
	std::shared_ptr<Walnut::Image> m_ImageOrig;
	virtual void OnAttach() override
	{
		m_ImageOrig = std::make_shared<Walnut::Image>(m_file_name);
	}
	virtual void OnUIRender() override
	{
		ImGui::Begin("Hello");
		ImGui::Button("Button");
               //change the image here for example we load and pass the data buffer to m_ImageOrig
		int width, height, channels;
		uint8_t* data = nullptr;
		uint64_t size = 0;

		if (stbi_is_hdr(m_file_name.c_str()))
		{
			data = (uint8_t*)stbi_loadf(m_file_name.c_str(), &width, &height, &channels, 4);
			size = width * height * 4 * sizeof(float);
			
		}
		else
		{
			data = stbi_load(m_file_name.c_str(), &width, &height, &channels, 4);
			size = width * height * 4;
			
		}
		m_ImageOrig->SetData(data);
		ImGui::Image(m_ImageOrig->GetDescriptorSet(), { (float)m_ImageOrig->GetWidth(),(float)m_ImageOrig->GetHeight() });
		ImGui::End();

		ImGui::ShowDemoWindow();
	}
};
```

Maybe there is a need to some Vulkan command barrier or fence? I am not an expert.

**Comment by TheCherno** [comment]
I've just pushed a fix for the resource free queue to make it per-frame-in-flight (https://github.com/TheCherno/Walnut/commit/b8df101f50a01d337e4a1abe52585fe5651262a5) - give it a go and see if this problem persists.

**Comment by TheCherno** [comment]
Upon a closer read of your problem, it had nothing to do with the resource free queue - the real fix is in my latest commit (https://github.com/TheCherno/Walnut/commit/9325ca5af9c3194b127d2fb6c263302c22910ad1)

**Comment by mwindowshz** [comment]
Thanks! @TheCherno 
**This fixed the bug**. no crash anymore.

Trying to understand the changes.
you added s_CurrentFrameIndex  for the currect swapchain image index

And I understand the fix is here when run loop needs to rebuild the swap chain.
```
// Resize swap chain?
if (g_SwapChainRebuild)
...
// Clear allocated command buffers from here since entire pool is destroyed
	s_AllocatedCommandBuffers.clear();
	s_AllocatedCommandBuffers.resize(g_MainWindowData.ImageCount);
```
So when rebuilding you clearing the command buffer list, and then resizing it.
but this is  done without calling VkFreeCommandBuffer? 
and also no allocation is done just resizing, 
Is this because in GetCommandBuffer() you allocate?

I see in GetCommandBuffer there is allocation
```
VkCommandBuffer& command_buffer = s_AllocatedCommandBuffers[wd->FrameIndex].emplace_back();
auto err = vkAllocateCommandBuffers(g_Device, &cmdBufAllocateInfo, &command_buffer);

```
Does this allocates the buffer? after the vector was just resized.

In the RenderFrame : threre is
```
// Free command buffers allocated by Application::GetCommandBuffer
// These use g_MainWindowData.FrameIndex and not s_CurrentFrameIndex because they're tied to the swapchain image index
auto& allocatedCommandBuffers = s_AllocatedCommandBuffers[wd->FrameIndex];
if (allocatedCommandBuffers.size() > 0)
{
	vkFreeCommandBuffers(g_Device, fd->CommandPool, (uint32_t)allocatedCommandBuffers.size(), 
       allocatedCommandBuffers.data());
			allocatedCommandBuffers.clear();
}
```
So do we need to vkFreeCommandBuffers, in the g_SwapChainRebuild situations or not? and why not.
Hope I understand this correctly. and what I am asking is clear.

Thanks again, for sharing this great project!

**Comment by mwindowshz** [comment]
closing this issue the fix works. Thanks
